# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: "en"
title: Didya Eat 
email: didyaeat.ny@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  .

minimal_mistakes_skin: "dirt"
search: true
logo: /assets/images/logo.png

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
#paginate: 20 # amount of posts to show
#paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

search: false

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-QYLVM2P09P"
#    anonymize_ip: false # default

og_image: /assets/images/logo.png

author:
  name   : "Vince"
  avatar : "/assets/images/pop.jpg"
  bio    : ""
  email: didyaeatny@gmail.com
  links:
    - label: "Home"
      icon: "fas fa-fw fa-link"
      url: "/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/didyaeatny/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/didyaeatny/"
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/UCITlXPrcvewDQYxEgJWOZTA"

footer:
  links:
    - label: "Home"
      icon: "fas fa-fw fa-home"
      url: "/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/didyaeatny/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/didyaeatny/"
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/UCITlXPrcvewDQYxEgJWOZTA"


excerpt: "More to Come [...]"
header:
  overlay_image: /assets/images/header.jpg
  overlay_filter: 0.5 # same as adding an opacity of 0.5 to a black background
  caption: "Pandemic Pedal Collection 2020-09-13"

collections_dir: /collections/

collections:
  blog:
    output: true
    title: Recipes
    position: 3

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: archive
      show_date: true
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
  # _blog
  - scope:
      path: ""
      type: blog
    values:
      layout: single
      #classes: wide
      show_date: true
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

